# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
#dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:zarquon42/ppa
  - sudo apt-get -q update
  - sudo apt-get install -y statismo-dev libinsighttoolkit4-dev libboost-date-time-dev libboost-system-dev libboost-thread-dev cmake libboost-program-options-dev libboost-filesystem-dev libfftw3-dev

repos:
  CRAN: https://cloud.r-project.org

r_binary_packages:
 - rgl
 - Rcpp
 - RcppEigen
 - RcppArmadillo
 - foreach

r_packages:
 - doParallel
 - yaImpute
 - testthat
 - colorRamps
 - Morpho
 - Rvcg
 - spam
 - spam64
 - lbfgs
 - colorspace

r_github_packages:
 - zarquon42b/RvtkStatismo

notifications:
  email:
    on_success: change
    on_failure: change



